export const OFFICIAL_PRACTICE_AREAS = [
  'Administrative Law','Admiralty and Maritime','Adoption','ADR Arbitration and Mediation',
  'Agriculture','Airplane Bus and Helicopter Accidents','Animal and Dog Bites','Antitrust',
  'Asbestos Mesothelioma','Assault and Battery (Plaintiff)','Auto Dealer Fraud','Aviation',
  'Bad Faith Insurance','Banking and Finance Law','Bankruptcy','Birth Injury','Brain Injury',
  'Business and Commercial Law','Business Organizations','Cannabis Law','Car Accidents',
  'Child Custody','Child Support','Civil Rights','Class Actions','Collaborative Law',
  'Collections','Communications and Media Law','Constitutional Law','Construction',
  'Construction Accident','Consumer Protection','Contracts','Copyrights','Credit Repair',
  'Criminal Defense','Dangerous Products','Debtor and Creditor','Defamation',
  'Disability Insurance','Discrimination','Divorce and Separation','Domestic Violence',
  'Drug Crime','Drugs and Medical Devices','DUI and DWI','Education','Elder Law',
  'Election Campaign and Political Law','Eminent Domain','Employment Law (Employer)',
  'Employment Rights','Entertainment Sports and Leisure Law','Environmental Law','ERISA',
  'Estate Planning','Ethics and Professional Responsibility','Family Law',"Father's Rights",
  'Federal and White Collar Crimes','Foreclosure and Alternatives','Franchising','Gaming',
  'Government Agencies and Programs','Government Contracts','Health Care Law',
  'Housing and Construction Defects','Immigration','Insurance Defense','Insurance Law',
  'International Law','Internet','Labor Law','Land Use and Zoning','Landlord and Tenant',
  'Legal Malpractice','Lemon Law','Litigation and Appeals','Medical Malpractice',
  'Mergers and Acquisitions','Military','Military Divorce','Motor Vehicle Defects',
  'Native Peoples','Natural Resources','Nursing Home Abuse','Oil Gas and Energy','Patents',
  'Personal Injury','Personal Injury Defense','Premises Liability','Probate',
  'Professional Malpractice','Railroad Worker Injury and FELA','Real Estate','Same Sex',
  'Science and Technology Law','Securities','Sex Crime','Sexual Abuse','Sexual Harassment',
  'Social Security','Social Security Disability','State Local and Municipal Law',
  'Tax Increment Financing','Tax Law','Toxic Mold','Toxic Torts','Trademarks',
  'Traffic Ticket','Transportation','Truck Accident','Trusts',"Veteran's Benefits",
  'Wage and Hour','Whistleblower and Qui Tam','Wills',"Workers' Compensation",
  'Wrongful Death','Wrongful Termination',
]
